# Generated by Django 5.0 on 2023-12-20 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='dateCompleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
